/** 简谱皮肤 key：一谱一套，仅用于 numberNotation */
export enum NumberNotationSkinKeyEnum {
    Measure = 'measure',

    Sharp = 'sharp',
    Flat = 'flat',
    Double_sharp = 'double_sharp',
    Double_flat = 'double_flat',
    Natural = 'natural',
    // 闭合线（单谱表第一小节左侧）
    Close_line = 'close_line',
    linked_close_line = 'linked_close_line',
    // 小节线
    Single_barline = 'single_barline',
    Double_barline = 'double_barline',
    StartRepeat_barline = 'startRepeat_barline',
    EndRepeat_barline = 'endRepeat_barline',
    Dashed_barline = 'dashed_barline',
    Final_barline = 'final_barline',
    Start_end_repeat_barline = 'start_end_repeat_barline',
    Dotted_barline = 'dotted_barline',
    Reverse_barline = 'reverse_barline',
    Heavy_barline = 'heavy_barline',
    Heavy_double_barline = 'heavy_double_barline',
    // 连谱小节线
    linked_single_barline = 'linked_single_barline',
    linked_double_barline = 'linked_double_barline',
    linked_startRepeat_barline = 'linked_startRepeat_barline',
    linked_endRepeat_barline = 'linked_endRepeat_barline',
    linked_dashed_barline = 'linked_dashed_barline',
    linked_final_barline = 'linked_final_barline',
    linked_start_end_repeat_barline = 'linked_start_end_repeat_barline',
    linked_dotted_barline = 'linked_dotted_barline',
    linked_reverse_barline = 'linked_reverse_barline',
    linked_heavy_barline = 'linked_heavy_barline',
    linked_heavy_double_barline = 'linked_heavy_double_barline',
    // 调号，这个皮肤做的时候按照treble去定位。代码里自动对其它谱号进行y值偏移
    C = 'C',
    C_sharp = 'C_sharp',
    D_flat = 'D_flat',
    D = 'D',
    E_flat = 'E_flat',
    E = 'E',
    F = 'F',
    F_sharp = 'F_sharp',
    G_flat = 'G_flat',
    G = 'G',
    A_flat = 'A_flat',
    A = 'A',
    B_flat = 'B_flat',
    B = 'B',
    C_flat = 'C_flat',
    // 拍号
    '1_1' = '1_1',
    '1_4' = '1_4',
    '2_4' = '2_4',
    '3_4' = '3_4',
    '4_4' = '4_4',
    '3_8' = '3_8',
    '6_8' = '6_8',

    AugmentationDot_1 = 'augmentationDot_1',
    AugmentationDot_2 = 'augmentationDot_2',
    AugmentationDot_3 = 'augmentationDot_3',
    // 简谱专用：数字 0-7、减时线、高/低音点线
    Number_0 = 'number_0',
    Number_1 = 'number_1',
    Number_2 = 'number_2',
    Number_3 = 'number_3',
    Number_4 = 'number_4',
    Number_5 = 'number_5',
    Number_6 = 'number_6',
    Number_7 = 'number_7',
    Number_X = 'number_X', // 节奏音符（无音高）
    ReduceLine_1 = 'reduceLine_1',
    ReduceLine_2 = 'reduceLine_2',
    ReduceLine_3 = 'reduceLine_3',
    ReduceLine_4 = 'reduceLine_4',
    ReduceLine_5 = 'reduceLine_5',
    ReduceLine_6 = 'reduceLine_6',
    addLine = 'addLine', // 简谱高/低音点下方的横线
    /** 八度点：音符上方=高八度，下方=低八度，每点表示一个八度 */
    OctaveDot = 'octaveDot',
    // 连谱号
    Bracket = 'bracket',
    Brace = 'brace',
    Square = 'square',
    // 反复符号
    Repeat_coda = 'repeat_coda',
    Repeat_to_coda = 'repeat_to_coda',
    Repeat_segno = 'repeat_segno',
    Repeat_dc = 'repeat_dc',
    Repeat_ds = 'repeat_ds',
    Repeat_fine = 'repeat_fine',
    Repeat_dc_al_fine = 'repeat_dc_al_fine',
    Repeat_dc_al_coda = 'repeat_dc_al_coda',
    Repeat_ds_al_fine = 'repeat_ds_al_fine',
    Repeat_ds_al_coda = 'repeat_ds_al_coda',
}
