/** 五线谱皮肤 key：一谱一套，仅用于 guitarTab */
export enum GuitarTabSkinKeyEnum {
  Measure = 'measure',

  // 闭合线（单谱表第一小节左侧）
  Close_line = 'close_line',
  linked_close_line = 'linked_close_line',
  // 小节线
  Single_barline = 'single_barline',
  Double_barline = 'double_barline',
  StartRepeat_barline = 'startRepeat_barline',
  EndRepeat_barline = 'endRepeat_barline',
  Dashed_barline = 'dashed_barline',
  Final_barline = 'final_barline',
  Start_end_repeat_barline = 'start_end_repeat_barline',
  Dotted_barline = 'dotted_barline',
  Reverse_barline = 'reverse_barline',
  Heavy_barline = 'heavy_barline',
  Heavy_double_barline = 'heavy_double_barline',
  // 连谱小节线
  linked_single_barline = 'linked_single_barline',
  linked_double_barline = 'linked_double_barline',
  linked_startRepeat_barline = 'linked_startRepeat_barline',
  linked_endRepeat_barline = 'linked_endRepeat_barline',
  linked_dashed_barline = 'linked_dashed_barline',
  linked_final_barline = 'linked_final_barline',
  linked_start_end_repeat_barline = 'linked_start_end_repeat_barline',
  linked_dotted_barline = 'linked_dotted_barline',
  linked_reverse_barline = 'linked_reverse_barline',
  linked_heavy_barline = 'linked_heavy_barline',
  linked_heavy_double_barline = 'linked_heavy_double_barline',
  // 拍号
  '2_4' = '2_4',
  '3_4' = '3_4',
  '4_4' = '4_4',
  '5_4' = '5_4',
  '6_4' = '6_4',
  '3_8' = '3_8',
  '4_8' = '4_8',
  '5_8' = '5_8',
  '6_8' = '6_8',
  '7_8' = '7_8',
  '9_8' = '9_8',
  '12_8' = '12_8',
  Common = 'common',
  Cut = 'cut',
  '2_2' = '2_2',
  '3_2' = '3_2',
  '4_2' = '4_2',
  // 音符
  Tab_note_x = 'tab_note_x',
  Tab_note_0 = 'tab_note_0',
  Tab_note_1 = 'tab_note_1',
  Tab_note_2 = 'tab_note_2',
  Tab_note_3 = 'tab_note_3',
  Tab_note_4 = 'tab_note_4',
  Tab_note_5 = 'tab_note_5',
  Tab_note_6 = 'tab_note_6',
  Tab_note_7 = 'tab_note_7',
  Tab_note_8 = 'tab_note_8',
  Tab_note_9 = 'tab_note_9',
  Tab_note_10 = 'tab_note_10',
  Tab_note_11 = 'tab_note_11',
  Tab_note_12 = 'tab_note_12',
  Tab_note_13 = 'tab_note_13',
  Tab_note_14 = 'tab_note_14',
  Tab_note_15 = 'tab_note_15',
  Tab_note_16 = 'tab_note_16',
  Tab_note_17 = 'tab_note_17',
  Tab_note_18 = 'tab_note_18',
  Tab_note_19 = 'tab_note_19',
  Tab_note_20 = 'tab_note_20',
  Tab_note_21 = 'tab_note_21',
  Tab_note_22 = 'tab_note_22',
  Tab_note_23 = 'tab_note_23',
  Tab_note_24 = 'tab_note_24',
  Tab_note_25 = 'tab_note_25',
  Tab_note_26 = 'tab_note_26',
  Tab_note_27 = 'tab_note_27',
  // 泛音（数字用 <> 包裹）
  Tab_harmonic_x = 'tab_harmonic_x',
  Tab_harmonic_0 = 'tab_harmonic_0',
  Tab_harmonic_1 = 'tab_harmonic_1',
  Tab_harmonic_2 = 'tab_harmonic_2',
  Tab_harmonic_3 = 'tab_harmonic_3',
  Tab_harmonic_4 = 'tab_harmonic_4',
  Tab_harmonic_5 = 'tab_harmonic_5',
  Tab_harmonic_6 = 'tab_harmonic_6',
  Tab_harmonic_7 = 'tab_harmonic_7',
  Tab_harmonic_8 = 'tab_harmonic_8',
  Tab_harmonic_9 = 'tab_harmonic_9',
  Tab_harmonic_10 = 'tab_harmonic_10',
  Tab_harmonic_11 = 'tab_harmonic_11',
  Tab_harmonic_12 = 'tab_harmonic_12',
  Tab_harmonic_13 = 'tab_harmonic_13',
  Tab_harmonic_14 = 'tab_harmonic_14',
  Tab_harmonic_15 = 'tab_harmonic_15',
  Tab_harmonic_16 = 'tab_harmonic_16',
  Tab_harmonic_17 = 'tab_harmonic_17',
  Tab_harmonic_18 = 'tab_harmonic_18',
  Tab_harmonic_19 = 'tab_harmonic_19',
  Tab_harmonic_20 = 'tab_harmonic_20',
  Tab_harmonic_21 = 'tab_harmonic_21',
  Tab_harmonic_22 = 'tab_harmonic_22',
  Tab_harmonic_23 = 'tab_harmonic_23',
  Tab_harmonic_24 = 'tab_harmonic_24',
  Tab_harmonic_25 = 'tab_harmonic_25',
  Tab_harmonic_26 = 'tab_harmonic_26',
  Tab_harmonic_27 = 'tab_harmonic_27',
  // 符干
  NoteStem = 'notestem',
  // 符尾
  NoteTail_1 = 'noteTail_1',
  NoteTail_2 = 'noteTail_2',
  NoteTail_3 = 'noteTail_3',
  NoteTail_4 = 'noteTail_4',
  NoteTail_5 = 'noteTail_5',
  NoteTail_6 = 'noteTail_6',
  // 休止符
  Rest_1 = 'rest_1',
  Rest_2 = 'rest_2',
  Rest_3 = 'rest_3',
  Rest_4 = 'rest_4',
  Rest_5 = 'rest_5',
  Rest_6 = 'rest_6',
  Rest_7 = 'rest_7',
  Rest_8 = 'rest_8',
  Rest_9 = 'rest_9',

  /** 增时线（二分/全音符等） */
  Addline = 'addline',
  // 附点
  AugmentationDot_1 = 'augmentationDot_1',
  AugmentationDot_2 = 'augmentationDot_2',
  AugmentationDot_3 = 'augmentationDot_3',
  // 连谱号
  Bracket = 'bracket', // 标准连谱号
  Brace = 'brace', // 大括号
  Square = 'square', // 中括号
  // 反复符号（不含反复小节线与 volta）
  Repeat_coda = 'repeat_coda',
  Repeat_to_coda = 'repeat_to_coda',
  Repeat_segno = 'repeat_segno',
  Repeat_dc = 'repeat_dc',
  Repeat_ds = 'repeat_ds',
  Repeat_fine = 'repeat_fine',
  Repeat_dc_al_fine = 'repeat_dc_al_fine',
  Repeat_dc_al_coda = 'repeat_dc_al_coda',
  Repeat_ds_al_fine = 'repeat_ds_al_fine',
  Repeat_ds_al_coda = 'repeat_ds_al_coda',
  /** 符杠（几何组件；content 为纯色，w/h=0） */
  NoteBeam = 'noteBeam',
  /** 连音线（几何组件；content 为纯色，w/h=0） */
  Slur = 'slur',
  /** 反复房子（几何组件；content 为纯色，w/h=0） */
  Volta = 'volta',
  // 单音符附属符号
  Accent_above = 'acccent_above',
  Staccato_above = 'staccato_above',
  Staccatissimo_above = 'staccato_above',
  Tenuto_above = 'tenuto_above',
  Loure_above = 'loure_above',
  Marcato_above = 'marcato_above',
  Accent_staccato_above = 'accent_staccato_above',
  Marcato_staccato_above = 'marcato_staccato_above',
  Marcato_tenuto_above = 'marcato_tenuto_above',
  Staccatissimo_stroke_above = 'staccatissimo_stroke_above',
  Staccatissimo_wedge_above = 'staccatissimo_wedge_above',
  Stress_above = 'stress_above',
  Tenuto_accent_above = 'tenuto_accent_above',
  Unstress_above = 'unstress_above',
  Open = 'open',
  Muted = 'muted',
  Harmonic = 'harmonic',
  Up_bow = 'up_bow',
  Down_bow = 'down_bow',
  // ornaments
  Turn = 'turn',
  InvertedTurn = 'invertedTurn',
  Trill = 'trill',
  ShortTrill = 'shortTrill',
  Mordent = 'mordent',
  // 扫弦
  Strumming = 'strumming',
  // Arpeggios
  Arpeggio = 'arpeggio',
  Up_arpeggio = 'up_arpeggio',
  Down_arpeggio = 'down_arpeggio',
  Bracket_arpeggio = 'bracket_arpeggio',
  Up_arpeggio_straight = 'up_arpeggio_straight',
  Down_arpeggio_straight = 'down_arpeggio_straight',
  // 和弦图
  TabChord = 'tab_chord',
  // 拍弦框
  Tab_slap = 'tab_slap',
  /** 推弦（几何组件；content 为纯色，w/h=0） */
  Bend = 'bend',
  // glissandos TODO 这个暂时不做
  // dynamics 强弱记号
  Dyn_PPP = 'dyn_ppp',
  Dyn_PP = 'dyn_pp',
  Dyn_P = 'dyn_p',
  Dyn_MP = 'dyn_mp',
  Dyn_MF = 'dyn_mf',
  Dyn_F = 'dyn_f',
  Dyn_FF = 'dyn_ff',
  Dyn_FFF = 'dyn_fff',
  Dyn_FP = 'dyn_fp',
  Dyn_PF = 'dyn_pf',
  Dyn_SF = 'dyn_sf',
  Dyn_SFZ = 'dyn_sfz',
  Dyn_SFF = 'dyn_sff',
  Dyn_SFFZ = 'dyn_sffz',
  Dyn_SFP = 'dyn_sfp',
  Dyn_RFZ = 'dyn_rfz',
  Dyn_RF = 'dyn_rf',
  Dyn_FZ = 'dyn_fz',
  // TODO 单小节附属符号没有皮肤，所以不写
}
