/** 五线谱皮肤 key：一谱一套，仅用于 guitarTab */
export enum GuitarTabSkinKeyEnum {
    Measure = 'measure',

    // 闭合线（单谱表第一小节左侧）
    Close_line = 'close_line',
    linked_close_line = 'linked_close_line',
    // 小节线
    Single_barline = 'single_barline',
    Double_barline = 'double_barline',
    StartRepeat_barline = 'startRepeat_barline',
    EndRepeat_barline = 'endRepeat_barline',
    Dashed_barline = 'dashed_barline',
    Final_barline = 'final_barline',
    Start_end_repeat_barline = 'start_end_repeat_barline',
    Dotted_barline = 'dotted_barline',
    Reverse_barline = 'reverse_barline',
    Heavy_barline = 'heavy_barline',
    Heavy_double_barline = 'heavy_double_barline',
    // 连谱小节线
    linked_single_barline = 'linked_single_barline',
    linked_double_barline = 'linked_double_barline',
    linked_startRepeat_barline = 'linked_startRepeat_barline',
    linked_endRepeat_barline = 'linked_endRepeat_barline',
    linked_dashed_barline = 'linked_dashed_barline',
    linked_final_barline = 'linked_final_barline',
    linked_start_end_repeat_barline = 'linked_start_end_repeat_barline',
    linked_dotted_barline = 'linked_dotted_barline',
    linked_reverse_barline = 'linked_reverse_barline',
    linked_heavy_barline = 'linked_heavy_barline',
    linked_heavy_double_barline = 'linked_heavy_double_barline',
    // 拍号
    '2_4' = '2_4',
    '3_4' = '3_4',
    '4_4' = '4_4',
    '5_4' = '5_4',
    '6_4' = '6_4',
    '3_8' = '3_8',
    '4_8' = '4_8',
    '5_8' = '5_8',
    '6_8' = '6_8',
    '7_8' = '7_8',
    '9_8' = '9_8',
    '12_8' = '12_8',
    Common = 'common',
    Cut = 'cut',
    '2_2' = '2_2',
    '3_2' = '3_2',
    '4_2' = '4_2',
    // 音符
    TabNote_x = 'tabNote_x',
    TabNote_0 = 'tabNote_0',
    TabNote_1 = 'tabNote_1',
    TabNote_2 = 'tabNote_2',
    TabNote_3 = 'tabNote_3',
    TabNote_4 = 'tabNote_4',
    TabNote_5 = 'tabNote_5',
    TabNote_6 = 'tabNote_6',
    TabNote_7 = 'tabNote_7',
    TabNote_8 = 'tabNote_8',
    TabNote_9 = 'tabNote_9',
    TabNote_10 = 'tabNote_10',
    TabNote_11 = 'tabNote_11',
    TabNote_12 = 'tabNote_12',
    TabNote_13 = 'tabNote_13',
    TabNote_14 = 'tabNote_14',
    TabNote_15 = 'tabNote_15',
    TabNote_16 = 'tabNote_16',
    TabNote_17 = 'tabNote_17',
    TabNote_18 = 'tabNote_18',
    TabNote_19 = 'tabNote_19',
    TabNote_20 = 'tabNote_20',
    TabNote_21 = 'tabNote_21',
    TabNote_22 = 'tabNote_22',
    TabNote_23 = 'tabNote_23',
    TabNote_24 = 'tabNote_24',
    TabNote_25 = 'tabNote_25',
    TabNote_26 = 'tabNote_26',
    TabNote_27 = 'tabNote_27',
    // 符干
    NoteStem = 'notestem',
    // 符尾
    NoteTail_1 = 'noteTail_1',
    NoteTail_2 = 'noteTail_2',
    NoteTail_3 = 'noteTail_3',
    NoteTail_4 = 'noteTail_4',
    NoteTail_5 = 'noteTail_5',
    NoteTail_6 = 'noteTail_6',
    // 休止符
    Rest_1 = 'rest_1',
    Rest_2 = 'rest_2',
    Rest_3 = 'rest_3',
    Rest_4 = 'rest_4',
    Rest_5 = 'rest_5',
    Rest_6 = 'rest_6',
    Rest_7 = 'rest_7',
    Rest_8 = 'rest_8',
    Rest_9 = 'rest_9',
    // 附点
    AugmentationDot_1 = 'augmentationDot_1',
    AugmentationDot_2 = 'augmentationDot_2',
    AugmentationDot_3 = 'augmentationDot_3',
    // 连谱号
    Bracket = 'bracket', // 标准连谱号
    Brace = 'brace', // 大括号
    Square = 'square', // 中括号
    // 反复符号（不含反复小节线与 volta）
    Repeat_coda = 'repeat_coda',
    Repeat_to_coda = 'repeat_to_coda',
    Repeat_segno = 'repeat_segno',
    Repeat_dc = 'repeat_dc',
    Repeat_ds = 'repeat_ds',
    Repeat_fine = 'repeat_fine',
    Repeat_dc_al_fine = 'repeat_dc_al_fine',
    Repeat_dc_al_coda = 'repeat_dc_al_coda',
    Repeat_ds_al_fine = 'repeat_ds_al_fine',
    Repeat_ds_al_coda = 'repeat_ds_al_coda',
    /** 符杠（几何组件；content 为纯色，w/h=0） */
    NoteBeam = 'noteBeam',
    /** 连音线（几何组件；content 为纯色，w/h=0） */
    Slur = 'slur',
    /** 反复房子（几何组件；content 为纯色，w/h=0） */
    Volta = 'volta',
    // 单音符附属符号
    Accent_above = 'acccent_above',
    Staccato_above = 'staccato_above',
    Staccatissimo_above = 'staccato_above',
    Tenuto_above = 'tenuto_above',
    Loure_above = 'loure_above',
    Marcato_above = 'marcato_above',
    Accent_staccato_above = 'accent_staccato_above',
    Marcato_staccato_above = 'marcato_staccato_above',
    Marcato_tenuto_above = 'marcato_tenuto_above',
    Staccatissimo_stroke_above = 'staccatissimo_stroke_above',
    Staccatissimo_wedge_above = 'staccatissimo_wedge_above',
    Stress_above = 'stress_above',
    Tenuto_accent_above = 'tenuto_accent_above',
    Unstress_above = 'unstress_above',
    Open = 'open',
    Muted = 'muted',
    Harmonic = 'harmonic',
    Up_bow = 'up_bow',
    Down_bow = 'down_bow',
    // ornaments
    Turn = 'turn',
    InvertedTurn = 'invertedTurn',
    Trill = 'trill',
    ShortTrill = 'shortTrill',
    Mordent = 'mordent',
    // Arpeggios
    Arpeggio = 'arpeggio',
    Up_arpeggio = 'up_arpeggio',
    Down_arpeggio = 'down_arpeggio',
    Bracket_arpeggio = 'bracket_arpeggio',
    Up_arpeggio_straight = 'up_arpeggio_straight',
    Down_arpeggio_straight = 'down_arpeggio_straight',
    // glissandos TODO 这个暂时不做
    // dynamics 强弱记号
    Dyn_PPP = 'dyn_ppp',
    Dyn_PP = 'dyn_pp',
    Dyn_P = 'dyn_p',
    Dyn_MP = 'dyn_mp',
    Dyn_MF = 'dyn_mf',
    Dyn_F = 'dyn_f',
    Dyn_FF = 'dyn_ff',
    Dyn_FFF = 'dyn_fff',
    Dyn_FP = 'dyn_fp',
    Dyn_PF = 'dyn_pf',
    Dyn_SF = 'dyn_sf',
    Dyn_SFZ = 'dyn_sfz',
    Dyn_SFF = 'dyn_sff',
    Dyn_SFFZ = 'dyn_sffz',
    Dyn_SFP = 'dyn_sfp',
    Dyn_RFZ = 'dyn_rfz',
    Dyn_RF = 'dyn_rf',
    Dyn_FZ = 'dyn_fz',
    // TODO 单小节附属符号没有皮肤，所以不写
}
