/**
 * 标准键盘的 KeyboardEvent.code 枚举
 * 适用于主键区、小键盘、功能键、方向键、修饰键等
 */
export enum KeyCodeEnum {
    // ===== 控制键 =====
    Escape = 'Escape',
    Tab = 'Tab',
    CapsLock = 'CapsLock',
    ShiftLeft = 'ShiftLeft',
    ShiftRight = 'ShiftRight',
    ControlLeft = 'ControlLeft',
    ControlRight = 'ControlRight',
    AltLeft = 'AltLeft',
    AltRight = 'AltRight',
    MetaLeft = 'MetaLeft',
    MetaRight = 'MetaRight',
    Space = 'Space',
    Enter = 'Enter',
    Backspace = 'Backspace',

    // ===== 数字区（主键区）=====
    Backquote = 'Backquote',
    Digit1 = 'Digit1',
    Digit2 = 'Digit2',
    Digit3 = 'Digit3',
    Digit4 = 'Digit4',
    Digit5 = 'Digit5',
    Digit6 = 'Digit6',
    Digit7 = 'Digit7',
    Digit8 = 'Digit8',
    Digit9 = 'Digit9',
    Digit0 = 'Digit0',
    Minus = 'Minus',
    Equal = 'Equal',

    // ===== 字母区 =====
    KeyQ = 'KeyQ',
    KeyW = 'KeyW',
    KeyE = 'KeyE',
    KeyR = 'KeyR',
    KeyT = 'KeyT',
    KeyY = 'KeyY',
    KeyU = 'KeyU',
    KeyI = 'KeyI',
    KeyO = 'KeyO',
    KeyP = 'KeyP',
    KeyA = 'KeyA',
    KeyS = 'KeyS',
    KeyD = 'KeyD',
    KeyF = 'KeyF',
    KeyG = 'KeyG',
    KeyH = 'KeyH',
    KeyJ = 'KeyJ',
    KeyK = 'KeyK',
    KeyL = 'KeyL',
    KeyZ = 'KeyZ',
    KeyX = 'KeyX',
    KeyC = 'KeyC',
    KeyV = 'KeyV',
    KeyB = 'KeyB',
    KeyN = 'KeyN',
    KeyM = 'KeyM',

    // ===== 标点区 =====
    BracketLeft = 'BracketLeft',
    BracketRight = 'BracketRight',
    Backslash = 'Backslash',
    Semicolon = 'Semicolon',
    Quote = 'Quote',
    Comma = 'Comma',
    Period = 'Period',
    Slash = 'Slash',

    // ===== 功能键 =====
    F1 = 'F1',
    F2 = 'F2',
    F3 = 'F3',
    F4 = 'F4',
    F5 = 'F5',
    F6 = 'F6',
    F7 = 'F7',
    F8 = 'F8',
    F9 = 'F9',
    F10 = 'F10',
    F11 = 'F11',
    F12 = 'F12',

    // ===== 导航键 =====
    Insert = 'Insert',
    Delete = 'Delete',
    Home = 'Home',
    End = 'End',
    PageUp = 'PageUp',
    PageDown = 'PageDown',
    ArrowUp = 'ArrowUp',
    ArrowDown = 'ArrowDown',
    ArrowLeft = 'ArrowLeft',
    ArrowRight = 'ArrowRight',

    // ===== 小键盘区 =====
    NumLock = 'NumLock',
    NumpadDivide = 'NumpadDivide',
    NumpadMultiply = 'NumpadMultiply',
    NumpadSubtract = 'NumpadSubtract',
    NumpadAdd = 'NumpadAdd',
    NumpadEnter = 'NumpadEnter',
    NumpadDecimal = 'NumpadDecimal',
    Numpad0 = 'Numpad0',
    Numpad1 = 'Numpad1',
    Numpad2 = 'Numpad2',
    Numpad3 = 'Numpad3',
    Numpad4 = 'Numpad4',
    Numpad5 = 'Numpad5',
    Numpad6 = 'Numpad6',
    Numpad7 = 'Numpad7',
    Numpad8 = 'Numpad8',
    Numpad9 = 'Numpad9',

    // ===== 其他特殊键 =====
    PrintScreen = 'PrintScreen',
    ScrollLock = 'ScrollLock',
    Pause = 'Pause',
    ContextMenu = 'ContextMenu',
    Convert = 'Convert',
    NonConvert = 'NonConvert',

    // 媒体键（有些键盘才有）
    AudioVolumeMute = 'AudioVolumeMute',
    AudioVolumeUp = 'AudioVolumeUp',
    AudioVolumeDown = 'AudioVolumeDown',
    MediaTrackNext = 'MediaTrackNext',
    MediaTrackPrevious = 'MediaTrackPrevious',
    MediaPlayPause = 'MediaPlayPause'
}
